[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer-runs = 200
solc = "0.8.19"
evm = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
fuzz = { runs = 256, max_test_rejects = 1_000_000 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
local = "http://localhost:8545"

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "4.8"
solmate = "6.8.0"
"@openzeppelin-contracts-upgradeable" = "4.8"
